name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup ESLint
        run: |
          npm install --save-dev npm install --save-dev typescript@5.1.6 eslint@7.32.0 eslint-plugin-react@7.32.2 eslint-plugin-react-hooks@4.6.0 eslint-plugin-import@2.27.5 @typescript-eslint/eslint-plugin@5.61.0 @typescript-eslint/parser@5.61.0 eslint-config-prettier@8.8.0
          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/borluv/linters-configuration/main/react-ts-sass/.eslintrc.json
      - name: ESLint Report
        run: npx eslint . --ext ts,tsx
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@15.10.0 stylelint-config-standard-scss@10.0.0 stylelint-config-css-modules@4.2.0
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/borluv/linters-configuration/main/react-ts-sass/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.scss"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
